/**
 * Pure functions that turn the token objects into a CSS custom-property string.
 *
 * The web app consumes CSS variables (light on `:root`, dark under
 * `[data-theme="dark"]`); native ignores this file entirely. Keeping generation
 * pure (no fs) makes it trivially testable and reusable at build time
 * (see emit-css.ts) or at runtime if ever needed.
 */

import { lightColors, darkColors } from "./color.js";
import type { ThemeColors } from "./color.js";
import { lightElevation, darkElevation } from "./elevation.js";
import { spacing, radii, borderWidth, sizing } from "./spacing.js";
import { fontSize, fontFamily, fontWeight, letterSpacing } from "./typography.js";

const colorVars = (c: ThemeColors): Record<string, string> => ({
  "--sl-color-bg": c.bg,
  "--sl-color-surface": c.surface,
  "--sl-color-surface-alt": c.surfaceAlt,
  "--sl-color-border": c.border,
  "--sl-color-text-primary": c.textPrimary,
  "--sl-color-text-secondary": c.textSecondary,
  "--sl-color-text-muted": c.textMuted,
  "--sl-color-accent": c.accent,
  "--sl-color-accent-hover": c.accentHover,
  "--sl-color-on-accent": c.onAccent,
  "--sl-color-accent-subtle": c.accentSubtle,
  "--sl-color-success": c.success,
  "--sl-color-success-subtle": c.successSubtle,
  "--sl-color-warning": c.warning,
  "--sl-color-warning-subtle": c.warningSubtle,
  "--sl-color-danger": c.danger,
  "--sl-color-danger-subtle": c.dangerSubtle,
  "--sl-color-info": c.info,
  "--sl-color-info-subtle": c.infoSubtle,
  "--sl-color-focus-ring": c.focusRing,
});

const elevationVars = (
  e: typeof lightElevation,
): Record<string, string> => ({
  "--sl-elevation-sm": e.sm.web,
  "--sl-elevation-md": e.md.web,
  "--sl-elevation-lg": e.lg.web,
});

/** Mode-agnostic vars (spacing/radii/type). Emitted once on :root. */
const staticVars = (): Record<string, string> => {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(spacing)) out[`--sl-space-${k}`] = `${v}px`;
  for (const [k, v] of Object.entries(radii))
    out[`--sl-radius-${k}`] = typeof v === "number" ? `${v}px` : v;
  for (const [k, v] of Object.entries(borderWidth)) out[`--sl-border-${k}`] = `${v}px`;
  for (const [k, v] of Object.entries(sizing)) out[`--sl-size-${k}`] = `${v}px`;
  for (const [k, v] of Object.entries(fontSize)) out[`--sl-font-size-${k}`] = `${v}px`;
  for (const [k, v] of Object.entries(fontWeight)) out[`--sl-font-weight-${k}`] = `${v}`;
  for (const [k, v] of Object.entries(letterSpacing)) out[`--sl-tracking-${k}`] = `${v}em`;
  out["--sl-font-display"] = fontFamily.display;
  out["--sl-font-body"] = fontFamily.body;
  out["--sl-font-mono"] = fontFamily.mono;
  return out;
};

const block = (selector: string, vars: Record<string, string>): string => {
  const body = Object.entries(vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n");
  return `${selector} {\n${body}\n}`;
};

/** Produce the full tokens.css contents. */
export function emitCss(): string {
  const root = { ...staticVars(), ...colorVars(lightColors), ...elevationVars(lightElevation) };
  const dark = { ...colorVars(darkColors), ...elevationVars(darkElevation) };
  return [
    "/* AUTO-GENERATED by @sitelink/tokens (src/emit-css.ts). Do not edit by hand. */",
    "/* Light theme is the default on :root; dark theme applies under [data-theme=\"dark\"]. */",
    "",
    block(":root", root),
    "",
    block('[data-theme="dark"]', dark),
    "",
  ].join("\n");
}
